/**
 * rwaFuturesService.js
 * SolFort-native RWA Futures — seeded products backed by internally registered assets.
 * Only assets already registered in our exchange are used as underlyings.
 */

export const RWA_FUTURES_PRODUCTS = [
  // ─── Hospitality ───────────────────────────────────────────────
  {
    symbol: 'CARMEN-PERP',
    assetId: 'seed-001',
    title: 'The Carmen Hotel',
    location: 'Playa del Carmen, Mexico',
    country: 'Mexico',
    category: 'hospitality',
    featuredImage: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    referencePrice: 1000,
    change24h: 2.34,
    volume24h: 182400,
    openInterest: 540000,
    leverageMin: 1,
    leverageMax: 5,
    contractType: 'Perpetual',
    fundingInfo: '0.01%/8h',
    tickSize: 0.10,
    settlementUnit: 'USDT',
    status: 'live',
    futuresEnabled: true,
    shortDescription: 'Luxury boutique hotel — Riviera Maya tourism corridor.',
    riskNotes: 'Tourism seasonality, FX (MXN/USD), Caribbean weather risk.',
    minOrderSize: 10,
  },
  {
    symbol: 'PUNTA-PERP',
    assetId: 'seed-005',
    title: 'Punta Cana 4',
    location: 'Punta Cana, Dominican Republic',
    country: 'Dominican Republic',
    category: 'hospitality',
    featuredImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    referencePrice: 100,
    change24h: 1.87,
    volume24h: 94800,
    openInterest: 310000,
    leverageMin: 1,
    leverageMax: 5,
    contractType: 'Perpetual',
    fundingInfo: '0.01%/8h',
    tickSize: 0.01,
    settlementUnit: 'USDT',
    status: 'live',
    futuresEnabled: true,
    shortDescription: 'Caribbean vacation rental — year-round tourist demand.',
    riskNotes: 'Seasonality, natural disaster exposure, DOP/EUR FX.',
    minOrderSize: 10,
  },
  {
    symbol: 'COAST-PERP',
    assetId: 'seed-007',
    title: 'Costa Mediterránea 1',
    location: 'Mediterranean Coast, Spain',
    country: 'Spain',
    category: 'hospitality',
    featuredImage: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    referencePrice: 100,
    change24h: 0.95,
    volume24h: 71200,
    openInterest: 240000,
    leverageMin: 1,
    leverageMax: 5,
    contractType: 'Perpetual',
    fundingInfo: '0.01%/8h',
    tickSize: 0.01,
    settlementUnit: 'USDT',
    status: 'upcoming',
    futuresEnabled: true,
    shortDescription: 'Coastal European residential — peak season vacation + long-term rental.',
    riskNotes: 'Spanish STR regulations, seasonal variability, EU real estate cycle.',
    minOrderSize: 10,
  },

  // ─── Residential ───────────────────────────────────────────────
  {
    symbol: 'DUBAI-PERP',
    assetId: 'seed-002',
    title: 'Dubai Marina Premium Residential',
    location: 'Dubai Marina, UAE',
    country: 'UAE',
    category: 'residential',
    featuredImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    referencePrice: 500,
    change24h: 3.12,
    volume24h: 428000,
    openInterest: 1240000,
    leverageMin: 1,
    leverageMax: 10,
    contractType: 'Perpetual',
    fundingInfo: '0.01%/8h',
    tickSize: 0.10,
    settlementUnit: 'USDT',
    status: 'live',
    futuresEnabled: true,
    shortDescription: 'High-yield Dubai Marina apartment — 92% occupancy, zero-tax jurisdiction.',
    riskNotes: 'UAE property market cycles, AED/USD peg, regulatory risk.',
    minOrderSize: 10,
  },
  {
    symbol: 'SALTA-PERP',
    assetId: 'seed-006',
    title: 'Salta 3',
    location: 'Salta, Argentina',
    country: 'Argentina',
    category: 'residential',
    featuredImage: 'https://images.unsplash.com/photo-1555636222-cae831e670b3?w=800&q=80',
    referencePrice: 100,
    change24h: -0.58,
    volume24h: 42000,
    openInterest: 118000,
    leverageMin: 1,
    leverageMax: 3,
    contractType: 'Perpetual',
    fundingInfo: '0.02%/8h',
    tickSize: 0.01,
    settlementUnit: 'USDT',
    status: 'live',
    futuresEnabled: true,
    shortDescription: 'Urban residential — Salta, Argentina. Stable local tenant base.',
    riskNotes: 'Argentine macro volatility, ARS inflation, FX risk.',
    minOrderSize: 10,
  },

  // ─── Commercial ────────────────────────────────────────────────
  {
    symbol: 'NYC-PERP',
    assetId: 'RE-MHT-1',
    title: 'Manhattan Office Tower',
    location: 'Midtown Manhattan, New York, USA',
    country: 'USA',
    category: 'commercial',
    featuredImage: 'https://images.unsplash.com/photo-1499092346589-b9b6be3e94b2?w=800&q=80',
    referencePrice: 247.50,
    change24h: 1.24,
    volume24h: 3840000,
    openInterest: 12400000,
    leverageMin: 1,
    leverageMax: 10,
    contractType: 'Perpetual',
    fundingInfo: '0.005%/8h',
    tickSize: 0.10,
    settlementUnit: 'USDT',
    status: 'live',
    futuresEnabled: true,
    shortDescription: 'Class A Midtown Manhattan office — Fortune 500 tenants, LEED Platinum.',
    riskNotes: 'Office market post-COVID softness, NYC regulatory environment.',
    minOrderSize: 10,
  },
  {
    symbol: 'LONDON-PERP',
    assetId: 'RE-LDN-1',
    title: 'London Mayfair Building',
    location: 'Mayfair, London, UK',
    country: 'United Kingdom',
    category: 'commercial',
    featuredImage: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&q=80',
    referencePrice: 312.80,
    change24h: 0.87,
    volume24h: 1940000,
    openInterest: 7600000,
    leverageMin: 1,
    leverageMax: 10,
    contractType: 'Perpetual',
    fundingInfo: '0.005%/8h',
    tickSize: 0.10,
    settlementUnit: 'USDT',
    status: 'live',
    futuresEnabled: true,
    shortDescription: 'Grade A Mayfair commercial — global financial institution tenants, BREEAM Excellent.',
    riskNotes: 'GBP FX risk, UK commercial property cycle, post-Brexit sentiment.',
    minOrderSize: 10,
  },

  // ─── Landmark ──────────────────────────────────────────────────
  {
    symbol: 'TOKYO-PERP',
    assetId: 'RE-TYO-1',
    title: 'Tokyo Ginza Retail',
    location: 'Ginza, Tokyo, Japan',
    country: 'Japan',
    category: 'landmark',
    featuredImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    referencePrice: 156.40,
    change24h: 3.45,
    volume24h: 2140000,
    openInterest: 8900000,
    leverageMin: 1,
    leverageMax: 10,
    contractType: 'Perpetual',
    fundingInfo: '0.005%/8h',
    tickSize: 0.10,
    settlementUnit: 'USDT',
    status: 'live',
    futuresEnabled: true,
    shortDescription: 'Ginza Chuo-dori flagship — world\'s most expensive retail street, luxury brand tenants.',
    riskNotes: 'JPY FX, Japan real estate cycle, luxury retail demand.',
    minOrderSize: 10,
  },
  {
    symbol: 'SINGA-PERP',
    assetId: 'RE-SGP-1',
    title: 'Singapore Marina Bay Tower',
    location: 'Marina Bay, Singapore',
    country: 'Singapore',
    category: 'landmark',
    featuredImage: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80',
    referencePrice: 198.60,
    change24h: 1.67,
    volume24h: 2840000,
    openInterest: 10200000,
    leverageMin: 1,
    leverageMax: 10,
    contractType: 'Perpetual',
    fundingInfo: '0.005%/8h',
    tickSize: 0.10,
    settlementUnit: 'USDT',
    status: 'live',
    futuresEnabled: true,
    shortDescription: 'AAA Marina Bay Financial Centre — Singapore prime CBD, MAS regulated.',
    riskNotes: 'SGD/USD, regional HQ tenant concentration, Singapore property cooling measures.',
    minOrderSize: 10,
  },
];

export const CATEGORY_CONFIG = {
  hospitality: { label: 'Hospitality', color: '#f59e0b', bg: 'rgba(245,158,11,0.1)' },
  residential:  { label: 'Residential',  color: '#22c55e', bg: 'rgba(34,197,94,0.1)' },
  commercial:   { label: 'Commercial',   color: '#3b82f6', bg: 'rgba(59,130,246,0.1)' },
  landmark:     { label: 'Landmark',     color: '#8b5cf6', bg: 'rgba(139,92,246,0.1)' },
};

export const STATUS_CONFIG = {
  live:     { label: 'LIVE',     color: '#22c55e', bg: 'rgba(34,197,94,0.12)' },
  upcoming: { label: 'UPCOMING', color: '#f59e0b', bg: 'rgba(245,158,11,0.12)' },
  paused:   { label: 'PAUSED',   color: '#ef4444', bg: 'rgba(239,68,68,0.12)' },
};

export function getProductBySymbol(symbol) {
  return RWA_FUTURES_PRODUCTS.find(p => p.symbol === symbol) || null;
}

export function getLiveProducts() {
  return RWA_FUTURES_PRODUCTS.filter(p => p.futuresEnabled);
}