export const LAUNCHPAD_PROJECTS = [
  {
    id: 1,
    name: 'SolInfra',
    ticker: 'SINF',
    category: 'Infrastructure',
    status: 'live',
    network: 'Solana',
    description: 'Decentralized infrastructure layer for high-throughput Solana dApps with auto-scaling node orchestration.',
    vision: 'SolInfra aims to become the backbone of Solana infrastructure — enabling any developer to deploy scalable, resilient dApp backends without managing servers.',
    problem: 'Current Solana dApps depend on centralized RPC providers, creating single points of failure and latency inconsistencies.',
    solution: 'SolInfra introduces a decentralized RPC mesh backed by staked node operators, achieving sub-10ms latency with 99.99% uptime guarantees.',
    raise: '$3.4M',
    target: '$5M',
    raised: 3400000,
    targetNum: 5000000,
    progress: 68,
    participants: 4120,
    price: '$0.08',
    launchDate: 'Mar 25, 2026',
    totalSupply: '1,000,000,000 SINF',
    launchAllocation: '15% (150M tokens)',
    minParticipation: '$50',
    maxParticipation: '$5,000',
    vesting: '20% TGE, 6-month linear vest',
    roi: null,
    roadmap: [
      { phase: 'Phase 1 — Foundation', date: 'Q1 2026', desc: 'Core protocol launch, node operator onboarding, testnet.', done: true },
      { phase: 'Phase 2 — Token Launch', date: 'Q1 2026', desc: 'SINF token launch, initial liquidity, launchpad raise.', done: false, current: true },
      { phase: 'Phase 3 — Mainnet', date: 'Q2 2026', desc: 'Full mainnet launch, 500+ node operators, SDK release.', done: false },
      { phase: 'Phase 4 — Ecosystem', date: 'Q3 2026', desc: 'Partner integrations, staking rewards, governance activation.', done: false },
    ],
    team: 'Founded by ex-Solana Labs and AWS engineers with 15+ years of combined distributed systems experience.',
    backers: 'Backed by Multicoin Capital, Solana Ventures, and Alameda Research alumni.',
    tokenUtility: 'SINF is used to pay for infrastructure credits, stake for node operator rights, and participate in protocol governance.',
  },
  {
    id: 2,
    name: 'RWABase',
    ticker: 'RWAB',
    category: 'RWA',
    status: 'live',
    network: 'Solana',
    description: 'On-chain tokenization protocol enabling compliant issuance and trading of real-world assets including real estate, bonds, and commodities.',
    vision: 'RWABase bridges the $500T traditional finance market with DeFi through compliant, auditable, and liquid tokenized instruments.',
    problem: 'Real-world assets are illiquid, fragmented, and inaccessible to retail investors globally.',
    solution: 'RWABase provides a permissioned issuance layer with KYC/AML integration, on-chain settlement, and secondary market liquidity pools.',
    raise: '$5.1M',
    target: '$8M',
    raised: 5100000,
    targetNum: 8000000,
    progress: 64,
    participants: 3210,
    price: '$0.12',
    launchDate: 'Apr 5, 2026',
    totalSupply: '500,000,000 RWAB',
    launchAllocation: '12% (60M tokens)',
    minParticipation: '$100',
    maxParticipation: '$10,000',
    vesting: '15% TGE, 9-month linear vest',
    roi: null,
    roadmap: [
      { phase: 'Phase 1 — Protocol Design', date: 'Q4 2025', desc: 'Smart contract architecture, legal framework, compliance partnerships.', done: true },
      { phase: 'Phase 2 — Token Launch', date: 'Q2 2026', desc: 'RWAB launch, initial asset listings, launchpad raise.', done: false, current: true },
      { phase: 'Phase 3 — Institutional Onboarding', date: 'Q3 2026', desc: 'First institutional asset tokenizations, legal wrappers complete.', done: false },
      { phase: 'Phase 4 — Global Expansion', date: 'Q4 2026', desc: 'Multi-jurisdiction support, DEX integrations, $1B AUM target.', done: false },
    ],
    team: 'Founded by fintech veterans from BlackRock, Deloitte, and Republic with deep RWA regulatory expertise.',
    backers: 'Strategic backing from Andreessen Horowitz (a16z), Hamilton Lane, and Franklin Templeton Digital.',
    tokenUtility: 'RWAB governs protocol parameters, earns revenue share from platform fees, and is required for institutional issuance licenses.',
  },
  {
    id: 3,
    name: 'NexYield',
    ticker: 'NEXY',
    category: 'DeFi',
    status: 'upcoming',
    network: 'Solana',
    description: 'Automated yield optimization protocol routing capital across DeFi strategies using AI-powered risk-adjusted return algorithms.',
    vision: 'NexYield democratizes institutional yield strategies by making them accessible on-chain with zero management overhead.',
    problem: 'Retail DeFi users lack the tools and expertise to optimize yields across fragmented protocols while managing risk.',
    solution: 'NexYield\'s AI engine continuously rebalances user capital across Solana\'s DeFi ecosystem — Raydium, Orca, Drift, and more — targeting optimal risk-adjusted APY.',
    raise: '-',
    target: '$3.5M',
    raised: 0,
    targetNum: 3500000,
    progress: 0,
    participants: 0,
    price: '$0.065',
    launchDate: 'Apr 18, 2026',
    totalSupply: '750,000,000 NEXY',
    launchAllocation: '10% (75M tokens)',
    minParticipation: '$25',
    maxParticipation: '$2,500',
    vesting: '25% TGE, 4-month linear vest',
    roi: null,
    roadmap: [
      { phase: 'Phase 1 — Research', date: 'Q4 2025', desc: 'AI model development, backtesting, protocol architecture.', done: true },
      { phase: 'Phase 2 — Testnet', date: 'Q1 2026', desc: 'Testnet launch, community yield vault testing.', done: true },
      { phase: 'Phase 3 — Token Launch', date: 'Q2 2026', desc: 'NEXY token launch, mainnet vaults, initial strategies.', done: false, current: true },
      { phase: 'Phase 4 — Scale', date: 'Q3 2026', desc: 'Multi-chain expansion, institutional vaults, DAO governance.', done: false },
    ],
    team: 'Team of quant analysts from Jane Street and Two Sigma building on-chain automation for DeFi.',
    backers: 'Backed by Pantera Capital, Dragonfly Capital, and Jump Crypto.',
    tokenUtility: 'NEXY governance token, fee sharing from vault profits, and boosts for stakers.',
  },
  {
    id: 4,
    name: 'ChainPulse AI',
    ticker: 'CPAI',
    category: 'AI',
    status: 'upcoming',
    network: 'Solana',
    description: 'Real-time on-chain analytics and AI-driven market intelligence platform for traders, institutions, and protocols.',
    vision: 'ChainPulse AI provides the Bloomberg Terminal of Web3 — combining on-chain data, social signals, and AI modeling into actionable intelligence.',
    problem: 'Crypto market data is fragmented across hundreds of chains and sources, making analysis slow, expensive, and incomplete.',
    solution: 'CPAI aggregates cross-chain data, applies ML models for pattern recognition, and delivers insights through an API, dashboard, and embedded widgets.',
    raise: '-',
    target: '$4.2M',
    raised: 0,
    targetNum: 4200000,
    progress: 0,
    participants: 0,
    price: '$0.045',
    launchDate: 'May 1, 2026',
    totalSupply: '2,000,000,000 CPAI',
    launchAllocation: '8% (160M tokens)',
    minParticipation: '$50',
    maxParticipation: '$3,000',
    vesting: '10% TGE, 12-month linear vest',
    roi: null,
    roadmap: [
      { phase: 'Phase 1 — Data Pipeline', date: 'Q3 2025', desc: 'Multi-chain data ingestion, normalization, storage.', done: true },
      { phase: 'Phase 2 — AI Engine', date: 'Q4 2025', desc: 'ML model training, signal generation, backtesting.', done: true },
      { phase: 'Phase 3 — Launch', date: 'Q2 2026', desc: 'Token launch, platform beta, API access.', done: false, current: true },
      { phase: 'Phase 4 — Enterprise', date: 'Q4 2026', desc: 'Enterprise API, institutional subscriptions, DAO.', done: false },
    ],
    team: 'Data scientists and engineers from Google DeepMind, Chainalysis, and Nansen.',
    backers: 'Backed by Paradigm, Spartan Group, and Coinbase Ventures.',
    tokenUtility: 'CPAI is required to access premium analytics tiers, pay for API credits, and participate in platform governance.',
  },
  {
    id: 5,
    name: 'EstateX',
    ticker: 'ESTX',
    category: 'RWA',
    status: 'completed',
    network: 'Solana',
    description: 'Fractional real estate investment platform enabling global access to tokenized premium properties from $10.',
    vision: 'EstateX makes premium real estate investment accessible to anyone worldwide, removing barriers of high minimums, geography, and illiquidity.',
    problem: 'Real estate has historically been accessible only to high-net-worth individuals due to high capital requirements and geographic limitations.',
    solution: 'EstateX tokenizes vetted premium properties into digital shares, enabling fractional ownership, instant liquidity, and automated yield distribution.',
    raise: '$6.8M',
    target: '$6.5M',
    raised: 6800000,
    targetNum: 6500000,
    progress: 100,
    participants: 7420,
    price: '$0.032',
    launchDate: 'Feb 10, 2026',
    totalSupply: '3,000,000,000 ESTX',
    launchAllocation: '10% (300M tokens)',
    minParticipation: '$10',
    maxParticipation: '$1,000',
    vesting: '30% TGE, 3-month linear vest',
    roi: '+240%',
    roadmap: [
      { phase: 'Phase 1 — Foundation', date: 'Q3 2025', desc: 'Legal setup, property tokenization framework, compliance.', done: true },
      { phase: 'Phase 2 — Token Launch', date: 'Q1 2026', desc: 'ESTX launch, first 5 properties tokenized, 103.8% raise.', done: true },
      { phase: 'Phase 3 — Expansion', date: 'Q2 2026', desc: 'Global property listings, yield distribution live.', done: false, current: true },
      { phase: 'Phase 4 — Ecosystem', date: 'Q3 2026', desc: 'Secondary market, staking, institutional partnerships.', done: false },
    ],
    team: 'Real estate and blockchain veterans from CBRE, Propy, and Lofty.ai.',
    backers: 'Backed by RealX Capital, Solana Ventures, and Republic Real Estate.',
    tokenUtility: 'ESTX holders receive proportional rental income, governance rights over property acquisitions, and fee discounts.',
  },
];

export const CATEGORY_COLORS = {
  Infrastructure: { bg: 'bg-orange-400/10', text: 'text-orange-400', border: 'border-orange-400/20' },
  AI:             { bg: 'bg-cyan-400/10',   text: 'text-cyan-400',   border: 'border-cyan-400/20'   },
  RWA:            { bg: 'bg-amber-400/10',  text: 'text-amber-400',  border: 'border-amber-400/20'  },
  DeFi:           { bg: 'bg-purple-400/10', text: 'text-purple-400', border: 'border-purple-400/20' },
  Gaming:         { bg: 'bg-green-400/10',  text: 'text-green-400',  border: 'border-green-400/20'  },
  Social:         { bg: 'bg-pink-400/10',   text: 'text-pink-400',   border: 'border-pink-400/20'   },
  'Solana Ecosystem': { bg: 'bg-[#9945FF]/10', text: 'text-[#9945FF]', border: 'border-[#9945FF]/20' },
};

export const STATUS_CONFIG = {
  live:      { label: 'Live',      color: 'bg-emerald-400/10 text-emerald-400 border-emerald-400/20' },
  upcoming:  { label: 'Upcoming',  color: 'bg-blue-400/10 text-blue-400 border-blue-400/20'         },
  completed: { label: 'Completed', color: 'bg-slate-400/10 text-slate-400 border-slate-400/20'      },
};